package com.xianyo.util.scenicmodule.dao.pojo;

import java.util.Date;

public class ScenicData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenicinfo_.scenicid
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    private Long scenicid;

    @Override
    public String toString() {
        return "ScenicData{" +
                "scenicid=" + scenicid +
                ", scenicname='" + scenicname + '\'' +
                ", scenicsynopsis='" + scenicsynopsis + '\'' +
                ", scenicpicdir='" + scenicpicdir + '\'' +
                ", foodscore=" + foodscore +
                ", foodofficialsorce=" + foodofficialsorce +
                ", trafficscore=" + trafficscore +
                ", trafficofficialscore=" + trafficofficialscore +
                ", entertainmentscore=" + entertainmentscore +
                ", entertainmentofficialscore=" + entertainmentofficialscore +
                ", culturalscore=" + culturalscore +
                ", culturalofficialscore=" + culturalofficialscore +
                ", sceneryscore=" + sceneryscore +
                ", sceneryofficialscore=" + sceneryofficialscore +
                ", totalscore=" + totalscore +
                ", totalofficialsocre=" + totalofficialsocre +
                ", gradenumber=" + gradenumber +
                ", vpnumber=" + vpnumber +
                ", validvpnumber=" + validvpnumber +
                ", userid=" + userid +
                ", state=" + state +
                ", date=" + date +
                ", reply='" + reply + '\'' +
                ", scenictraffic='" + scenictraffic + '\'' +
                ", scenicfood='" + scenicfood + '\'' +
                '}';
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenicinfo_.scenicName
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    private String scenicname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenicinfo_.scenicsynopsis
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    private String scenicsynopsis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenicinfo_.scenicPicDir
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    private String scenicpicdir;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenicinfo_.foodScore
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    private Float foodscore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenicinfo_.foodOfficialSorce
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    private Float foodofficialsorce;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenicinfo_.trafficScore
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    private Float trafficscore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenicinfo_.trafficOfficialScore
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    private Float trafficofficialscore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenicinfo_.entertainmentScore
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    private Float entertainmentscore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenicinfo_.entertainmentOfficialScore
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    private Float entertainmentofficialscore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenicinfo_.culturalScore
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    private Float culturalscore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenicinfo_.culturalOfficialScore
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    private Float culturalofficialscore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenicinfo_.sceneryScore
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    private Float sceneryscore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenicinfo_.sceneryOfficialScore
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    private Float sceneryofficialscore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenicinfo_.totalScore
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    private Float totalscore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenicinfo_.totalOfficialSocre
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    private Float totalofficialsocre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenicinfo_.gradeNumber
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    private Integer gradenumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenicinfo_.vpNumber
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    private Integer vpnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenicinfo_.validVPNumber
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    private Integer validvpnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenicinfo_.userid
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenicinfo_.state
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenicinfo_.date
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenicinfo_.reply
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    private String reply;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenicinfo_.scenictraffic
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    private String scenictraffic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scenicinfo_.scenicfood
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    private String scenicfood;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenicinfo_.scenicid
     *
     * @return the value of scenicinfo_.scenicid
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    public Long getScenicid() {
        return scenicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenicinfo_.scenicid
     *
     * @param scenicid the value for scenicinfo_.scenicid
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    public void setScenicid(Long scenicid) {
        this.scenicid = scenicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenicinfo_.scenicName
     *
     * @return the value of scenicinfo_.scenicName
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    public String getScenicname() {
        return scenicname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenicinfo_.scenicName
     *
     * @param scenicname the value for scenicinfo_.scenicName
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    public void setScenicname(String scenicname) {
        this.scenicname = scenicname == null ? null : scenicname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenicinfo_.scenicsynopsis
     *
     * @return the value of scenicinfo_.scenicsynopsis
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    public String getScenicsynopsis() {
        return scenicsynopsis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenicinfo_.scenicsynopsis
     *
     * @param scenicsynopsis the value for scenicinfo_.scenicsynopsis
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    public void setScenicsynopsis(String scenicsynopsis) {
        this.scenicsynopsis = scenicsynopsis == null ? null : scenicsynopsis.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenicinfo_.scenicPicDir
     *
     * @return the value of scenicinfo_.scenicPicDir
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    public String getScenicpicdir() {
        return scenicpicdir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenicinfo_.scenicPicDir
     *
     * @param scenicpicdir the value for scenicinfo_.scenicPicDir
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    public void setScenicpicdir(String scenicpicdir) {
        this.scenicpicdir = scenicpicdir == null ? null : scenicpicdir.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenicinfo_.foodScore
     *
     * @return the value of scenicinfo_.foodScore
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    public Float getFoodscore() {
        return foodscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenicinfo_.foodScore
     *
     * @param foodscore the value for scenicinfo_.foodScore
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    public void setFoodscore(Float foodscore) {
        this.foodscore = foodscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenicinfo_.foodOfficialSorce
     *
     * @return the value of scenicinfo_.foodOfficialSorce
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    public Float getFoodofficialsorce() {
        return foodofficialsorce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenicinfo_.foodOfficialSorce
     *
     * @param foodofficialsorce the value for scenicinfo_.foodOfficialSorce
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    public void setFoodofficialsorce(Float foodofficialsorce) {
        this.foodofficialsorce = foodofficialsorce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenicinfo_.trafficScore
     *
     * @return the value of scenicinfo_.trafficScore
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    public Float getTrafficscore() {
        return trafficscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenicinfo_.trafficScore
     *
     * @param trafficscore the value for scenicinfo_.trafficScore
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    public void setTrafficscore(Float trafficscore) {
        this.trafficscore = trafficscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenicinfo_.trafficOfficialScore
     *
     * @return the value of scenicinfo_.trafficOfficialScore
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    public Float getTrafficofficialscore() {
        return trafficofficialscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenicinfo_.trafficOfficialScore
     *
     * @param trafficofficialscore the value for scenicinfo_.trafficOfficialScore
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    public void setTrafficofficialscore(Float trafficofficialscore) {
        this.trafficofficialscore = trafficofficialscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenicinfo_.entertainmentScore
     *
     * @return the value of scenicinfo_.entertainmentScore
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    public Float getEntertainmentscore() {
        return entertainmentscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenicinfo_.entertainmentScore
     *
     * @param entertainmentscore the value for scenicinfo_.entertainmentScore
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    public void setEntertainmentscore(Float entertainmentscore) {
        this.entertainmentscore = entertainmentscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenicinfo_.entertainmentOfficialScore
     *
     * @return the value of scenicinfo_.entertainmentOfficialScore
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    public Float getEntertainmentofficialscore() {
        return entertainmentofficialscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenicinfo_.entertainmentOfficialScore
     *
     * @param entertainmentofficialscore the value for scenicinfo_.entertainmentOfficialScore
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    public void setEntertainmentofficialscore(Float entertainmentofficialscore) {
        this.entertainmentofficialscore = entertainmentofficialscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenicinfo_.culturalScore
     *
     * @return the value of scenicinfo_.culturalScore
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    public Float getCulturalscore() {
        return culturalscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenicinfo_.culturalScore
     *
     * @param culturalscore the value for scenicinfo_.culturalScore
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    public void setCulturalscore(Float culturalscore) {
        this.culturalscore = culturalscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenicinfo_.culturalOfficialScore
     *
     * @return the value of scenicinfo_.culturalOfficialScore
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    public Float getCulturalofficialscore() {
        return culturalofficialscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenicinfo_.culturalOfficialScore
     *
     * @param culturalofficialscore the value for scenicinfo_.culturalOfficialScore
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    public void setCulturalofficialscore(Float culturalofficialscore) {
        this.culturalofficialscore = culturalofficialscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenicinfo_.sceneryScore
     *
     * @return the value of scenicinfo_.sceneryScore
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    public Float getSceneryscore() {
        return sceneryscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenicinfo_.sceneryScore
     *
     * @param sceneryscore the value for scenicinfo_.sceneryScore
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    public void setSceneryscore(Float sceneryscore) {
        this.sceneryscore = sceneryscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenicinfo_.sceneryOfficialScore
     *
     * @return the value of scenicinfo_.sceneryOfficialScore
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    public Float getSceneryofficialscore() {
        return sceneryofficialscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenicinfo_.sceneryOfficialScore
     *
     * @param sceneryofficialscore the value for scenicinfo_.sceneryOfficialScore
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    public void setSceneryofficialscore(Float sceneryofficialscore) {
        this.sceneryofficialscore = sceneryofficialscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenicinfo_.totalScore
     *
     * @return the value of scenicinfo_.totalScore
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    public Float getTotalscore() {
        return totalscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenicinfo_.totalScore
     *
     * @param totalscore the value for scenicinfo_.totalScore
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    public void setTotalscore(Float totalscore) {
        this.totalscore = totalscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenicinfo_.totalOfficialSocre
     *
     * @return the value of scenicinfo_.totalOfficialSocre
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    public Float getTotalofficialsocre() {
        return totalofficialsocre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenicinfo_.totalOfficialSocre
     *
     * @param totalofficialsocre the value for scenicinfo_.totalOfficialSocre
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    public void setTotalofficialsocre(Float totalofficialsocre) {
        this.totalofficialsocre = totalofficialsocre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenicinfo_.gradeNumber
     *
     * @return the value of scenicinfo_.gradeNumber
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    public Integer getGradenumber() {
        return gradenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenicinfo_.gradeNumber
     *
     * @param gradenumber the value for scenicinfo_.gradeNumber
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    public void setGradenumber(Integer gradenumber) {
        this.gradenumber = gradenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenicinfo_.vpNumber
     *
     * @return the value of scenicinfo_.vpNumber
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    public Integer getVpnumber() {
        return vpnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenicinfo_.vpNumber
     *
     * @param vpnumber the value for scenicinfo_.vpNumber
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    public void setVpnumber(Integer vpnumber) {
        this.vpnumber = vpnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenicinfo_.validVPNumber
     *
     * @return the value of scenicinfo_.validVPNumber
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    public Integer getValidvpnumber() {
        return validvpnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenicinfo_.validVPNumber
     *
     * @param validvpnumber the value for scenicinfo_.validVPNumber
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    public void setValidvpnumber(Integer validvpnumber) {
        this.validvpnumber = validvpnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenicinfo_.userid
     *
     * @return the value of scenicinfo_.userid
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenicinfo_.userid
     *
     * @param userid the value for scenicinfo_.userid
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenicinfo_.state
     *
     * @return the value of scenicinfo_.state
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenicinfo_.state
     *
     * @param state the value for scenicinfo_.state
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenicinfo_.date
     *
     * @return the value of scenicinfo_.date
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenicinfo_.date
     *
     * @param date the value for scenicinfo_.date
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenicinfo_.reply
     *
     * @return the value of scenicinfo_.reply
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    public String getReply() {
        return reply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenicinfo_.reply
     *
     * @param reply the value for scenicinfo_.reply
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    public void setReply(String reply) {
        this.reply = reply == null ? null : reply.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenicinfo_.scenictraffic
     *
     * @return the value of scenicinfo_.scenictraffic
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    public String getScenictraffic() {
        return scenictraffic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenicinfo_.scenictraffic
     *
     * @param scenictraffic the value for scenicinfo_.scenictraffic
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    public void setScenictraffic(String scenictraffic) {
        this.scenictraffic = scenictraffic == null ? null : scenictraffic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scenicinfo_.scenicfood
     *
     * @return the value of scenicinfo_.scenicfood
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    public String getScenicfood() {
        return scenicfood;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scenicinfo_.scenicfood
     *
     * @param scenicfood the value for scenicinfo_.scenicfood
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    public void setScenicfood(String scenicfood) {
        this.scenicfood = scenicfood == null ? null : scenicfood.trim();
    }
}