package com.xianyo.util.scenicmodule.dao.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ScenicDataExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table scenicinfo_
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table scenicinfo_
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table scenicinfo_
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenicinfo_
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    public ScenicDataExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenicinfo_
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenicinfo_
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenicinfo_
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenicinfo_
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenicinfo_
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenicinfo_
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenicinfo_
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenicinfo_
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenicinfo_
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scenicinfo_
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table scenicinfo_
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andScenicidIsNull() {
            addCriterion("scenicid is null");
            return (Criteria) this;
        }

        public Criteria andScenicidIsNotNull() {
            addCriterion("scenicid is not null");
            return (Criteria) this;
        }

        public Criteria andScenicidEqualTo(Long value) {
            addCriterion("scenicid =", value, "scenicid");
            return (Criteria) this;
        }

        public Criteria andScenicidNotEqualTo(Long value) {
            addCriterion("scenicid <>", value, "scenicid");
            return (Criteria) this;
        }

        public Criteria andScenicidGreaterThan(Long value) {
            addCriterion("scenicid >", value, "scenicid");
            return (Criteria) this;
        }

        public Criteria andScenicidGreaterThanOrEqualTo(Long value) {
            addCriterion("scenicid >=", value, "scenicid");
            return (Criteria) this;
        }

        public Criteria andScenicidLessThan(Long value) {
            addCriterion("scenicid <", value, "scenicid");
            return (Criteria) this;
        }

        public Criteria andScenicidLessThanOrEqualTo(Long value) {
            addCriterion("scenicid <=", value, "scenicid");
            return (Criteria) this;
        }

        public Criteria andScenicidIn(List<Long> values) {
            addCriterion("scenicid in", values, "scenicid");
            return (Criteria) this;
        }

        public Criteria andScenicidNotIn(List<Long> values) {
            addCriterion("scenicid not in", values, "scenicid");
            return (Criteria) this;
        }

        public Criteria andScenicidBetween(Long value1, Long value2) {
            addCriterion("scenicid between", value1, value2, "scenicid");
            return (Criteria) this;
        }

        public Criteria andScenicidNotBetween(Long value1, Long value2) {
            addCriterion("scenicid not between", value1, value2, "scenicid");
            return (Criteria) this;
        }

        public Criteria andScenicnameIsNull() {
            addCriterion("scenicName is null");
            return (Criteria) this;
        }

        public Criteria andScenicnameIsNotNull() {
            addCriterion("scenicName is not null");
            return (Criteria) this;
        }

        public Criteria andScenicnameEqualTo(String value) {
            addCriterion("scenicName =", value, "scenicname");
            return (Criteria) this;
        }

        public Criteria andScenicnameNotEqualTo(String value) {
            addCriterion("scenicName <>", value, "scenicname");
            return (Criteria) this;
        }

        public Criteria andScenicnameGreaterThan(String value) {
            addCriterion("scenicName >", value, "scenicname");
            return (Criteria) this;
        }

        public Criteria andScenicnameGreaterThanOrEqualTo(String value) {
            addCriterion("scenicName >=", value, "scenicname");
            return (Criteria) this;
        }

        public Criteria andScenicnameLessThan(String value) {
            addCriterion("scenicName <", value, "scenicname");
            return (Criteria) this;
        }

        public Criteria andScenicnameLessThanOrEqualTo(String value) {
            addCriterion("scenicName <=", value, "scenicname");
            return (Criteria) this;
        }

        public Criteria andScenicnameLike(String value) {
            addCriterion("scenicName like", value, "scenicname");
            return (Criteria) this;
        }

        public Criteria andScenicnameNotLike(String value) {
            addCriterion("scenicName not like", value, "scenicname");
            return (Criteria) this;
        }

        public Criteria andScenicnameIn(List<String> values) {
            addCriterion("scenicName in", values, "scenicname");
            return (Criteria) this;
        }

        public Criteria andScenicnameNotIn(List<String> values) {
            addCriterion("scenicName not in", values, "scenicname");
            return (Criteria) this;
        }

        public Criteria andScenicnameBetween(String value1, String value2) {
            addCriterion("scenicName between", value1, value2, "scenicname");
            return (Criteria) this;
        }

        public Criteria andScenicnameNotBetween(String value1, String value2) {
            addCriterion("scenicName not between", value1, value2, "scenicname");
            return (Criteria) this;
        }

        public Criteria andScenicsynopsisIsNull() {
            addCriterion("scenicsynopsis is null");
            return (Criteria) this;
        }

        public Criteria andScenicsynopsisIsNotNull() {
            addCriterion("scenicsynopsis is not null");
            return (Criteria) this;
        }

        public Criteria andScenicsynopsisEqualTo(String value) {
            addCriterion("scenicsynopsis =", value, "scenicsynopsis");
            return (Criteria) this;
        }

        public Criteria andScenicsynopsisNotEqualTo(String value) {
            addCriterion("scenicsynopsis <>", value, "scenicsynopsis");
            return (Criteria) this;
        }

        public Criteria andScenicsynopsisGreaterThan(String value) {
            addCriterion("scenicsynopsis >", value, "scenicsynopsis");
            return (Criteria) this;
        }

        public Criteria andScenicsynopsisGreaterThanOrEqualTo(String value) {
            addCriterion("scenicsynopsis >=", value, "scenicsynopsis");
            return (Criteria) this;
        }

        public Criteria andScenicsynopsisLessThan(String value) {
            addCriterion("scenicsynopsis <", value, "scenicsynopsis");
            return (Criteria) this;
        }

        public Criteria andScenicsynopsisLessThanOrEqualTo(String value) {
            addCriterion("scenicsynopsis <=", value, "scenicsynopsis");
            return (Criteria) this;
        }

        public Criteria andScenicsynopsisLike(String value) {
            addCriterion("scenicsynopsis like", value, "scenicsynopsis");
            return (Criteria) this;
        }

        public Criteria andScenicsynopsisNotLike(String value) {
            addCriterion("scenicsynopsis not like", value, "scenicsynopsis");
            return (Criteria) this;
        }

        public Criteria andScenicsynopsisIn(List<String> values) {
            addCriterion("scenicsynopsis in", values, "scenicsynopsis");
            return (Criteria) this;
        }

        public Criteria andScenicsynopsisNotIn(List<String> values) {
            addCriterion("scenicsynopsis not in", values, "scenicsynopsis");
            return (Criteria) this;
        }

        public Criteria andScenicsynopsisBetween(String value1, String value2) {
            addCriterion("scenicsynopsis between", value1, value2, "scenicsynopsis");
            return (Criteria) this;
        }

        public Criteria andScenicsynopsisNotBetween(String value1, String value2) {
            addCriterion("scenicsynopsis not between", value1, value2, "scenicsynopsis");
            return (Criteria) this;
        }

        public Criteria andScenicpicdirIsNull() {
            addCriterion("scenicPicDir is null");
            return (Criteria) this;
        }

        public Criteria andScenicpicdirIsNotNull() {
            addCriterion("scenicPicDir is not null");
            return (Criteria) this;
        }

        public Criteria andScenicpicdirEqualTo(String value) {
            addCriterion("scenicPicDir =", value, "scenicpicdir");
            return (Criteria) this;
        }

        public Criteria andScenicpicdirNotEqualTo(String value) {
            addCriterion("scenicPicDir <>", value, "scenicpicdir");
            return (Criteria) this;
        }

        public Criteria andScenicpicdirGreaterThan(String value) {
            addCriterion("scenicPicDir >", value, "scenicpicdir");
            return (Criteria) this;
        }

        public Criteria andScenicpicdirGreaterThanOrEqualTo(String value) {
            addCriterion("scenicPicDir >=", value, "scenicpicdir");
            return (Criteria) this;
        }

        public Criteria andScenicpicdirLessThan(String value) {
            addCriterion("scenicPicDir <", value, "scenicpicdir");
            return (Criteria) this;
        }

        public Criteria andScenicpicdirLessThanOrEqualTo(String value) {
            addCriterion("scenicPicDir <=", value, "scenicpicdir");
            return (Criteria) this;
        }

        public Criteria andScenicpicdirLike(String value) {
            addCriterion("scenicPicDir like", value, "scenicpicdir");
            return (Criteria) this;
        }

        public Criteria andScenicpicdirNotLike(String value) {
            addCriterion("scenicPicDir not like", value, "scenicpicdir");
            return (Criteria) this;
        }

        public Criteria andScenicpicdirIn(List<String> values) {
            addCriterion("scenicPicDir in", values, "scenicpicdir");
            return (Criteria) this;
        }

        public Criteria andScenicpicdirNotIn(List<String> values) {
            addCriterion("scenicPicDir not in", values, "scenicpicdir");
            return (Criteria) this;
        }

        public Criteria andScenicpicdirBetween(String value1, String value2) {
            addCriterion("scenicPicDir between", value1, value2, "scenicpicdir");
            return (Criteria) this;
        }

        public Criteria andScenicpicdirNotBetween(String value1, String value2) {
            addCriterion("scenicPicDir not between", value1, value2, "scenicpicdir");
            return (Criteria) this;
        }

        public Criteria andFoodscoreIsNull() {
            addCriterion("foodScore is null");
            return (Criteria) this;
        }

        public Criteria andFoodscoreIsNotNull() {
            addCriterion("foodScore is not null");
            return (Criteria) this;
        }

        public Criteria andFoodscoreEqualTo(Float value) {
            addCriterion("foodScore =", value, "foodscore");
            return (Criteria) this;
        }

        public Criteria andFoodscoreNotEqualTo(Float value) {
            addCriterion("foodScore <>", value, "foodscore");
            return (Criteria) this;
        }

        public Criteria andFoodscoreGreaterThan(Float value) {
            addCriterion("foodScore >", value, "foodscore");
            return (Criteria) this;
        }

        public Criteria andFoodscoreGreaterThanOrEqualTo(Float value) {
            addCriterion("foodScore >=", value, "foodscore");
            return (Criteria) this;
        }

        public Criteria andFoodscoreLessThan(Float value) {
            addCriterion("foodScore <", value, "foodscore");
            return (Criteria) this;
        }

        public Criteria andFoodscoreLessThanOrEqualTo(Float value) {
            addCriterion("foodScore <=", value, "foodscore");
            return (Criteria) this;
        }

        public Criteria andFoodscoreIn(List<Float> values) {
            addCriterion("foodScore in", values, "foodscore");
            return (Criteria) this;
        }

        public Criteria andFoodscoreNotIn(List<Float> values) {
            addCriterion("foodScore not in", values, "foodscore");
            return (Criteria) this;
        }

        public Criteria andFoodscoreBetween(Float value1, Float value2) {
            addCriterion("foodScore between", value1, value2, "foodscore");
            return (Criteria) this;
        }

        public Criteria andFoodscoreNotBetween(Float value1, Float value2) {
            addCriterion("foodScore not between", value1, value2, "foodscore");
            return (Criteria) this;
        }

        public Criteria andFoodofficialsorceIsNull() {
            addCriterion("foodOfficialSorce is null");
            return (Criteria) this;
        }

        public Criteria andFoodofficialsorceIsNotNull() {
            addCriterion("foodOfficialSorce is not null");
            return (Criteria) this;
        }

        public Criteria andFoodofficialsorceEqualTo(Float value) {
            addCriterion("foodOfficialSorce =", value, "foodofficialsorce");
            return (Criteria) this;
        }

        public Criteria andFoodofficialsorceNotEqualTo(Float value) {
            addCriterion("foodOfficialSorce <>", value, "foodofficialsorce");
            return (Criteria) this;
        }

        public Criteria andFoodofficialsorceGreaterThan(Float value) {
            addCriterion("foodOfficialSorce >", value, "foodofficialsorce");
            return (Criteria) this;
        }

        public Criteria andFoodofficialsorceGreaterThanOrEqualTo(Float value) {
            addCriterion("foodOfficialSorce >=", value, "foodofficialsorce");
            return (Criteria) this;
        }

        public Criteria andFoodofficialsorceLessThan(Float value) {
            addCriterion("foodOfficialSorce <", value, "foodofficialsorce");
            return (Criteria) this;
        }

        public Criteria andFoodofficialsorceLessThanOrEqualTo(Float value) {
            addCriterion("foodOfficialSorce <=", value, "foodofficialsorce");
            return (Criteria) this;
        }

        public Criteria andFoodofficialsorceIn(List<Float> values) {
            addCriterion("foodOfficialSorce in", values, "foodofficialsorce");
            return (Criteria) this;
        }

        public Criteria andFoodofficialsorceNotIn(List<Float> values) {
            addCriterion("foodOfficialSorce not in", values, "foodofficialsorce");
            return (Criteria) this;
        }

        public Criteria andFoodofficialsorceBetween(Float value1, Float value2) {
            addCriterion("foodOfficialSorce between", value1, value2, "foodofficialsorce");
            return (Criteria) this;
        }

        public Criteria andFoodofficialsorceNotBetween(Float value1, Float value2) {
            addCriterion("foodOfficialSorce not between", value1, value2, "foodofficialsorce");
            return (Criteria) this;
        }

        public Criteria andTrafficscoreIsNull() {
            addCriterion("trafficScore is null");
            return (Criteria) this;
        }

        public Criteria andTrafficscoreIsNotNull() {
            addCriterion("trafficScore is not null");
            return (Criteria) this;
        }

        public Criteria andTrafficscoreEqualTo(Float value) {
            addCriterion("trafficScore =", value, "trafficscore");
            return (Criteria) this;
        }

        public Criteria andTrafficscoreNotEqualTo(Float value) {
            addCriterion("trafficScore <>", value, "trafficscore");
            return (Criteria) this;
        }

        public Criteria andTrafficscoreGreaterThan(Float value) {
            addCriterion("trafficScore >", value, "trafficscore");
            return (Criteria) this;
        }

        public Criteria andTrafficscoreGreaterThanOrEqualTo(Float value) {
            addCriterion("trafficScore >=", value, "trafficscore");
            return (Criteria) this;
        }

        public Criteria andTrafficscoreLessThan(Float value) {
            addCriterion("trafficScore <", value, "trafficscore");
            return (Criteria) this;
        }

        public Criteria andTrafficscoreLessThanOrEqualTo(Float value) {
            addCriterion("trafficScore <=", value, "trafficscore");
            return (Criteria) this;
        }

        public Criteria andTrafficscoreIn(List<Float> values) {
            addCriterion("trafficScore in", values, "trafficscore");
            return (Criteria) this;
        }

        public Criteria andTrafficscoreNotIn(List<Float> values) {
            addCriterion("trafficScore not in", values, "trafficscore");
            return (Criteria) this;
        }

        public Criteria andTrafficscoreBetween(Float value1, Float value2) {
            addCriterion("trafficScore between", value1, value2, "trafficscore");
            return (Criteria) this;
        }

        public Criteria andTrafficscoreNotBetween(Float value1, Float value2) {
            addCriterion("trafficScore not between", value1, value2, "trafficscore");
            return (Criteria) this;
        }

        public Criteria andTrafficofficialscoreIsNull() {
            addCriterion("trafficOfficialScore is null");
            return (Criteria) this;
        }

        public Criteria andTrafficofficialscoreIsNotNull() {
            addCriterion("trafficOfficialScore is not null");
            return (Criteria) this;
        }

        public Criteria andTrafficofficialscoreEqualTo(Float value) {
            addCriterion("trafficOfficialScore =", value, "trafficofficialscore");
            return (Criteria) this;
        }

        public Criteria andTrafficofficialscoreNotEqualTo(Float value) {
            addCriterion("trafficOfficialScore <>", value, "trafficofficialscore");
            return (Criteria) this;
        }

        public Criteria andTrafficofficialscoreGreaterThan(Float value) {
            addCriterion("trafficOfficialScore >", value, "trafficofficialscore");
            return (Criteria) this;
        }

        public Criteria andTrafficofficialscoreGreaterThanOrEqualTo(Float value) {
            addCriterion("trafficOfficialScore >=", value, "trafficofficialscore");
            return (Criteria) this;
        }

        public Criteria andTrafficofficialscoreLessThan(Float value) {
            addCriterion("trafficOfficialScore <", value, "trafficofficialscore");
            return (Criteria) this;
        }

        public Criteria andTrafficofficialscoreLessThanOrEqualTo(Float value) {
            addCriterion("trafficOfficialScore <=", value, "trafficofficialscore");
            return (Criteria) this;
        }

        public Criteria andTrafficofficialscoreIn(List<Float> values) {
            addCriterion("trafficOfficialScore in", values, "trafficofficialscore");
            return (Criteria) this;
        }

        public Criteria andTrafficofficialscoreNotIn(List<Float> values) {
            addCriterion("trafficOfficialScore not in", values, "trafficofficialscore");
            return (Criteria) this;
        }

        public Criteria andTrafficofficialscoreBetween(Float value1, Float value2) {
            addCriterion("trafficOfficialScore between", value1, value2, "trafficofficialscore");
            return (Criteria) this;
        }

        public Criteria andTrafficofficialscoreNotBetween(Float value1, Float value2) {
            addCriterion("trafficOfficialScore not between", value1, value2, "trafficofficialscore");
            return (Criteria) this;
        }

        public Criteria andEntertainmentscoreIsNull() {
            addCriterion("entertainmentScore is null");
            return (Criteria) this;
        }

        public Criteria andEntertainmentscoreIsNotNull() {
            addCriterion("entertainmentScore is not null");
            return (Criteria) this;
        }

        public Criteria andEntertainmentscoreEqualTo(Float value) {
            addCriterion("entertainmentScore =", value, "entertainmentscore");
            return (Criteria) this;
        }

        public Criteria andEntertainmentscoreNotEqualTo(Float value) {
            addCriterion("entertainmentScore <>", value, "entertainmentscore");
            return (Criteria) this;
        }

        public Criteria andEntertainmentscoreGreaterThan(Float value) {
            addCriterion("entertainmentScore >", value, "entertainmentscore");
            return (Criteria) this;
        }

        public Criteria andEntertainmentscoreGreaterThanOrEqualTo(Float value) {
            addCriterion("entertainmentScore >=", value, "entertainmentscore");
            return (Criteria) this;
        }

        public Criteria andEntertainmentscoreLessThan(Float value) {
            addCriterion("entertainmentScore <", value, "entertainmentscore");
            return (Criteria) this;
        }

        public Criteria andEntertainmentscoreLessThanOrEqualTo(Float value) {
            addCriterion("entertainmentScore <=", value, "entertainmentscore");
            return (Criteria) this;
        }

        public Criteria andEntertainmentscoreIn(List<Float> values) {
            addCriterion("entertainmentScore in", values, "entertainmentscore");
            return (Criteria) this;
        }

        public Criteria andEntertainmentscoreNotIn(List<Float> values) {
            addCriterion("entertainmentScore not in", values, "entertainmentscore");
            return (Criteria) this;
        }

        public Criteria andEntertainmentscoreBetween(Float value1, Float value2) {
            addCriterion("entertainmentScore between", value1, value2, "entertainmentscore");
            return (Criteria) this;
        }

        public Criteria andEntertainmentscoreNotBetween(Float value1, Float value2) {
            addCriterion("entertainmentScore not between", value1, value2, "entertainmentscore");
            return (Criteria) this;
        }

        public Criteria andEntertainmentofficialscoreIsNull() {
            addCriterion("entertainmentOfficialScore is null");
            return (Criteria) this;
        }

        public Criteria andEntertainmentofficialscoreIsNotNull() {
            addCriterion("entertainmentOfficialScore is not null");
            return (Criteria) this;
        }

        public Criteria andEntertainmentofficialscoreEqualTo(Float value) {
            addCriterion("entertainmentOfficialScore =", value, "entertainmentofficialscore");
            return (Criteria) this;
        }

        public Criteria andEntertainmentofficialscoreNotEqualTo(Float value) {
            addCriterion("entertainmentOfficialScore <>", value, "entertainmentofficialscore");
            return (Criteria) this;
        }

        public Criteria andEntertainmentofficialscoreGreaterThan(Float value) {
            addCriterion("entertainmentOfficialScore >", value, "entertainmentofficialscore");
            return (Criteria) this;
        }

        public Criteria andEntertainmentofficialscoreGreaterThanOrEqualTo(Float value) {
            addCriterion("entertainmentOfficialScore >=", value, "entertainmentofficialscore");
            return (Criteria) this;
        }

        public Criteria andEntertainmentofficialscoreLessThan(Float value) {
            addCriterion("entertainmentOfficialScore <", value, "entertainmentofficialscore");
            return (Criteria) this;
        }

        public Criteria andEntertainmentofficialscoreLessThanOrEqualTo(Float value) {
            addCriterion("entertainmentOfficialScore <=", value, "entertainmentofficialscore");
            return (Criteria) this;
        }

        public Criteria andEntertainmentofficialscoreIn(List<Float> values) {
            addCriterion("entertainmentOfficialScore in", values, "entertainmentofficialscore");
            return (Criteria) this;
        }

        public Criteria andEntertainmentofficialscoreNotIn(List<Float> values) {
            addCriterion("entertainmentOfficialScore not in", values, "entertainmentofficialscore");
            return (Criteria) this;
        }

        public Criteria andEntertainmentofficialscoreBetween(Float value1, Float value2) {
            addCriterion("entertainmentOfficialScore between", value1, value2, "entertainmentofficialscore");
            return (Criteria) this;
        }

        public Criteria andEntertainmentofficialscoreNotBetween(Float value1, Float value2) {
            addCriterion("entertainmentOfficialScore not between", value1, value2, "entertainmentofficialscore");
            return (Criteria) this;
        }

        public Criteria andCulturalscoreIsNull() {
            addCriterion("culturalScore is null");
            return (Criteria) this;
        }

        public Criteria andCulturalscoreIsNotNull() {
            addCriterion("culturalScore is not null");
            return (Criteria) this;
        }

        public Criteria andCulturalscoreEqualTo(Float value) {
            addCriterion("culturalScore =", value, "culturalscore");
            return (Criteria) this;
        }

        public Criteria andCulturalscoreNotEqualTo(Float value) {
            addCriterion("culturalScore <>", value, "culturalscore");
            return (Criteria) this;
        }

        public Criteria andCulturalscoreGreaterThan(Float value) {
            addCriterion("culturalScore >", value, "culturalscore");
            return (Criteria) this;
        }

        public Criteria andCulturalscoreGreaterThanOrEqualTo(Float value) {
            addCriterion("culturalScore >=", value, "culturalscore");
            return (Criteria) this;
        }

        public Criteria andCulturalscoreLessThan(Float value) {
            addCriterion("culturalScore <", value, "culturalscore");
            return (Criteria) this;
        }

        public Criteria andCulturalscoreLessThanOrEqualTo(Float value) {
            addCriterion("culturalScore <=", value, "culturalscore");
            return (Criteria) this;
        }

        public Criteria andCulturalscoreIn(List<Float> values) {
            addCriterion("culturalScore in", values, "culturalscore");
            return (Criteria) this;
        }

        public Criteria andCulturalscoreNotIn(List<Float> values) {
            addCriterion("culturalScore not in", values, "culturalscore");
            return (Criteria) this;
        }

        public Criteria andCulturalscoreBetween(Float value1, Float value2) {
            addCriterion("culturalScore between", value1, value2, "culturalscore");
            return (Criteria) this;
        }

        public Criteria andCulturalscoreNotBetween(Float value1, Float value2) {
            addCriterion("culturalScore not between", value1, value2, "culturalscore");
            return (Criteria) this;
        }

        public Criteria andCulturalofficialscoreIsNull() {
            addCriterion("culturalOfficialScore is null");
            return (Criteria) this;
        }

        public Criteria andCulturalofficialscoreIsNotNull() {
            addCriterion("culturalOfficialScore is not null");
            return (Criteria) this;
        }

        public Criteria andCulturalofficialscoreEqualTo(Float value) {
            addCriterion("culturalOfficialScore =", value, "culturalofficialscore");
            return (Criteria) this;
        }

        public Criteria andCulturalofficialscoreNotEqualTo(Float value) {
            addCriterion("culturalOfficialScore <>", value, "culturalofficialscore");
            return (Criteria) this;
        }

        public Criteria andCulturalofficialscoreGreaterThan(Float value) {
            addCriterion("culturalOfficialScore >", value, "culturalofficialscore");
            return (Criteria) this;
        }

        public Criteria andCulturalofficialscoreGreaterThanOrEqualTo(Float value) {
            addCriterion("culturalOfficialScore >=", value, "culturalofficialscore");
            return (Criteria) this;
        }

        public Criteria andCulturalofficialscoreLessThan(Float value) {
            addCriterion("culturalOfficialScore <", value, "culturalofficialscore");
            return (Criteria) this;
        }

        public Criteria andCulturalofficialscoreLessThanOrEqualTo(Float value) {
            addCriterion("culturalOfficialScore <=", value, "culturalofficialscore");
            return (Criteria) this;
        }

        public Criteria andCulturalofficialscoreIn(List<Float> values) {
            addCriterion("culturalOfficialScore in", values, "culturalofficialscore");
            return (Criteria) this;
        }

        public Criteria andCulturalofficialscoreNotIn(List<Float> values) {
            addCriterion("culturalOfficialScore not in", values, "culturalofficialscore");
            return (Criteria) this;
        }

        public Criteria andCulturalofficialscoreBetween(Float value1, Float value2) {
            addCriterion("culturalOfficialScore between", value1, value2, "culturalofficialscore");
            return (Criteria) this;
        }

        public Criteria andCulturalofficialscoreNotBetween(Float value1, Float value2) {
            addCriterion("culturalOfficialScore not between", value1, value2, "culturalofficialscore");
            return (Criteria) this;
        }

        public Criteria andSceneryscoreIsNull() {
            addCriterion("sceneryScore is null");
            return (Criteria) this;
        }

        public Criteria andSceneryscoreIsNotNull() {
            addCriterion("sceneryScore is not null");
            return (Criteria) this;
        }

        public Criteria andSceneryscoreEqualTo(Float value) {
            addCriterion("sceneryScore =", value, "sceneryscore");
            return (Criteria) this;
        }

        public Criteria andSceneryscoreNotEqualTo(Float value) {
            addCriterion("sceneryScore <>", value, "sceneryscore");
            return (Criteria) this;
        }

        public Criteria andSceneryscoreGreaterThan(Float value) {
            addCriterion("sceneryScore >", value, "sceneryscore");
            return (Criteria) this;
        }

        public Criteria andSceneryscoreGreaterThanOrEqualTo(Float value) {
            addCriterion("sceneryScore >=", value, "sceneryscore");
            return (Criteria) this;
        }

        public Criteria andSceneryscoreLessThan(Float value) {
            addCriterion("sceneryScore <", value, "sceneryscore");
            return (Criteria) this;
        }

        public Criteria andSceneryscoreLessThanOrEqualTo(Float value) {
            addCriterion("sceneryScore <=", value, "sceneryscore");
            return (Criteria) this;
        }

        public Criteria andSceneryscoreIn(List<Float> values) {
            addCriterion("sceneryScore in", values, "sceneryscore");
            return (Criteria) this;
        }

        public Criteria andSceneryscoreNotIn(List<Float> values) {
            addCriterion("sceneryScore not in", values, "sceneryscore");
            return (Criteria) this;
        }

        public Criteria andSceneryscoreBetween(Float value1, Float value2) {
            addCriterion("sceneryScore between", value1, value2, "sceneryscore");
            return (Criteria) this;
        }

        public Criteria andSceneryscoreNotBetween(Float value1, Float value2) {
            addCriterion("sceneryScore not between", value1, value2, "sceneryscore");
            return (Criteria) this;
        }

        public Criteria andSceneryofficialscoreIsNull() {
            addCriterion("sceneryOfficialScore is null");
            return (Criteria) this;
        }

        public Criteria andSceneryofficialscoreIsNotNull() {
            addCriterion("sceneryOfficialScore is not null");
            return (Criteria) this;
        }

        public Criteria andSceneryofficialscoreEqualTo(Float value) {
            addCriterion("sceneryOfficialScore =", value, "sceneryofficialscore");
            return (Criteria) this;
        }

        public Criteria andSceneryofficialscoreNotEqualTo(Float value) {
            addCriterion("sceneryOfficialScore <>", value, "sceneryofficialscore");
            return (Criteria) this;
        }

        public Criteria andSceneryofficialscoreGreaterThan(Float value) {
            addCriterion("sceneryOfficialScore >", value, "sceneryofficialscore");
            return (Criteria) this;
        }

        public Criteria andSceneryofficialscoreGreaterThanOrEqualTo(Float value) {
            addCriterion("sceneryOfficialScore >=", value, "sceneryofficialscore");
            return (Criteria) this;
        }

        public Criteria andSceneryofficialscoreLessThan(Float value) {
            addCriterion("sceneryOfficialScore <", value, "sceneryofficialscore");
            return (Criteria) this;
        }

        public Criteria andSceneryofficialscoreLessThanOrEqualTo(Float value) {
            addCriterion("sceneryOfficialScore <=", value, "sceneryofficialscore");
            return (Criteria) this;
        }

        public Criteria andSceneryofficialscoreIn(List<Float> values) {
            addCriterion("sceneryOfficialScore in", values, "sceneryofficialscore");
            return (Criteria) this;
        }

        public Criteria andSceneryofficialscoreNotIn(List<Float> values) {
            addCriterion("sceneryOfficialScore not in", values, "sceneryofficialscore");
            return (Criteria) this;
        }

        public Criteria andSceneryofficialscoreBetween(Float value1, Float value2) {
            addCriterion("sceneryOfficialScore between", value1, value2, "sceneryofficialscore");
            return (Criteria) this;
        }

        public Criteria andSceneryofficialscoreNotBetween(Float value1, Float value2) {
            addCriterion("sceneryOfficialScore not between", value1, value2, "sceneryofficialscore");
            return (Criteria) this;
        }

        public Criteria andTotalscoreIsNull() {
            addCriterion("totalScore is null");
            return (Criteria) this;
        }

        public Criteria andTotalscoreIsNotNull() {
            addCriterion("totalScore is not null");
            return (Criteria) this;
        }

        public Criteria andTotalscoreEqualTo(Float value) {
            addCriterion("totalScore =", value, "totalscore");
            return (Criteria) this;
        }

        public Criteria andTotalscoreNotEqualTo(Float value) {
            addCriterion("totalScore <>", value, "totalscore");
            return (Criteria) this;
        }

        public Criteria andTotalscoreGreaterThan(Float value) {
            addCriterion("totalScore >", value, "totalscore");
            return (Criteria) this;
        }

        public Criteria andTotalscoreGreaterThanOrEqualTo(Float value) {
            addCriterion("totalScore >=", value, "totalscore");
            return (Criteria) this;
        }

        public Criteria andTotalscoreLessThan(Float value) {
            addCriterion("totalScore <", value, "totalscore");
            return (Criteria) this;
        }

        public Criteria andTotalscoreLessThanOrEqualTo(Float value) {
            addCriterion("totalScore <=", value, "totalscore");
            return (Criteria) this;
        }

        public Criteria andTotalscoreIn(List<Float> values) {
            addCriterion("totalScore in", values, "totalscore");
            return (Criteria) this;
        }

        public Criteria andTotalscoreNotIn(List<Float> values) {
            addCriterion("totalScore not in", values, "totalscore");
            return (Criteria) this;
        }

        public Criteria andTotalscoreBetween(Float value1, Float value2) {
            addCriterion("totalScore between", value1, value2, "totalscore");
            return (Criteria) this;
        }

        public Criteria andTotalscoreNotBetween(Float value1, Float value2) {
            addCriterion("totalScore not between", value1, value2, "totalscore");
            return (Criteria) this;
        }

        public Criteria andTotalofficialsocreIsNull() {
            addCriterion("totalOfficialSocre is null");
            return (Criteria) this;
        }

        public Criteria andTotalofficialsocreIsNotNull() {
            addCriterion("totalOfficialSocre is not null");
            return (Criteria) this;
        }

        public Criteria andTotalofficialsocreEqualTo(Float value) {
            addCriterion("totalOfficialSocre =", value, "totalofficialsocre");
            return (Criteria) this;
        }

        public Criteria andTotalofficialsocreNotEqualTo(Float value) {
            addCriterion("totalOfficialSocre <>", value, "totalofficialsocre");
            return (Criteria) this;
        }

        public Criteria andTotalofficialsocreGreaterThan(Float value) {
            addCriterion("totalOfficialSocre >", value, "totalofficialsocre");
            return (Criteria) this;
        }

        public Criteria andTotalofficialsocreGreaterThanOrEqualTo(Float value) {
            addCriterion("totalOfficialSocre >=", value, "totalofficialsocre");
            return (Criteria) this;
        }

        public Criteria andTotalofficialsocreLessThan(Float value) {
            addCriterion("totalOfficialSocre <", value, "totalofficialsocre");
            return (Criteria) this;
        }

        public Criteria andTotalofficialsocreLessThanOrEqualTo(Float value) {
            addCriterion("totalOfficialSocre <=", value, "totalofficialsocre");
            return (Criteria) this;
        }

        public Criteria andTotalofficialsocreIn(List<Float> values) {
            addCriterion("totalOfficialSocre in", values, "totalofficialsocre");
            return (Criteria) this;
        }

        public Criteria andTotalofficialsocreNotIn(List<Float> values) {
            addCriterion("totalOfficialSocre not in", values, "totalofficialsocre");
            return (Criteria) this;
        }

        public Criteria andTotalofficialsocreBetween(Float value1, Float value2) {
            addCriterion("totalOfficialSocre between", value1, value2, "totalofficialsocre");
            return (Criteria) this;
        }

        public Criteria andTotalofficialsocreNotBetween(Float value1, Float value2) {
            addCriterion("totalOfficialSocre not between", value1, value2, "totalofficialsocre");
            return (Criteria) this;
        }

        public Criteria andGradenumberIsNull() {
            addCriterion("gradeNumber is null");
            return (Criteria) this;
        }

        public Criteria andGradenumberIsNotNull() {
            addCriterion("gradeNumber is not null");
            return (Criteria) this;
        }

        public Criteria andGradenumberEqualTo(Integer value) {
            addCriterion("gradeNumber =", value, "gradenumber");
            return (Criteria) this;
        }

        public Criteria andGradenumberNotEqualTo(Integer value) {
            addCriterion("gradeNumber <>", value, "gradenumber");
            return (Criteria) this;
        }

        public Criteria andGradenumberGreaterThan(Integer value) {
            addCriterion("gradeNumber >", value, "gradenumber");
            return (Criteria) this;
        }

        public Criteria andGradenumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("gradeNumber >=", value, "gradenumber");
            return (Criteria) this;
        }

        public Criteria andGradenumberLessThan(Integer value) {
            addCriterion("gradeNumber <", value, "gradenumber");
            return (Criteria) this;
        }

        public Criteria andGradenumberLessThanOrEqualTo(Integer value) {
            addCriterion("gradeNumber <=", value, "gradenumber");
            return (Criteria) this;
        }

        public Criteria andGradenumberIn(List<Integer> values) {
            addCriterion("gradeNumber in", values, "gradenumber");
            return (Criteria) this;
        }

        public Criteria andGradenumberNotIn(List<Integer> values) {
            addCriterion("gradeNumber not in", values, "gradenumber");
            return (Criteria) this;
        }

        public Criteria andGradenumberBetween(Integer value1, Integer value2) {
            addCriterion("gradeNumber between", value1, value2, "gradenumber");
            return (Criteria) this;
        }

        public Criteria andGradenumberNotBetween(Integer value1, Integer value2) {
            addCriterion("gradeNumber not between", value1, value2, "gradenumber");
            return (Criteria) this;
        }

        public Criteria andVpnumberIsNull() {
            addCriterion("vpNumber is null");
            return (Criteria) this;
        }

        public Criteria andVpnumberIsNotNull() {
            addCriterion("vpNumber is not null");
            return (Criteria) this;
        }

        public Criteria andVpnumberEqualTo(Integer value) {
            addCriterion("vpNumber =", value, "vpnumber");
            return (Criteria) this;
        }

        public Criteria andVpnumberNotEqualTo(Integer value) {
            addCriterion("vpNumber <>", value, "vpnumber");
            return (Criteria) this;
        }

        public Criteria andVpnumberGreaterThan(Integer value) {
            addCriterion("vpNumber >", value, "vpnumber");
            return (Criteria) this;
        }

        public Criteria andVpnumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("vpNumber >=", value, "vpnumber");
            return (Criteria) this;
        }

        public Criteria andVpnumberLessThan(Integer value) {
            addCriterion("vpNumber <", value, "vpnumber");
            return (Criteria) this;
        }

        public Criteria andVpnumberLessThanOrEqualTo(Integer value) {
            addCriterion("vpNumber <=", value, "vpnumber");
            return (Criteria) this;
        }

        public Criteria andVpnumberIn(List<Integer> values) {
            addCriterion("vpNumber in", values, "vpnumber");
            return (Criteria) this;
        }

        public Criteria andVpnumberNotIn(List<Integer> values) {
            addCriterion("vpNumber not in", values, "vpnumber");
            return (Criteria) this;
        }

        public Criteria andVpnumberBetween(Integer value1, Integer value2) {
            addCriterion("vpNumber between", value1, value2, "vpnumber");
            return (Criteria) this;
        }

        public Criteria andVpnumberNotBetween(Integer value1, Integer value2) {
            addCriterion("vpNumber not between", value1, value2, "vpnumber");
            return (Criteria) this;
        }

        public Criteria andValidvpnumberIsNull() {
            addCriterion("validVPNumber is null");
            return (Criteria) this;
        }

        public Criteria andValidvpnumberIsNotNull() {
            addCriterion("validVPNumber is not null");
            return (Criteria) this;
        }

        public Criteria andValidvpnumberEqualTo(Integer value) {
            addCriterion("validVPNumber =", value, "validvpnumber");
            return (Criteria) this;
        }

        public Criteria andValidvpnumberNotEqualTo(Integer value) {
            addCriterion("validVPNumber <>", value, "validvpnumber");
            return (Criteria) this;
        }

        public Criteria andValidvpnumberGreaterThan(Integer value) {
            addCriterion("validVPNumber >", value, "validvpnumber");
            return (Criteria) this;
        }

        public Criteria andValidvpnumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("validVPNumber >=", value, "validvpnumber");
            return (Criteria) this;
        }

        public Criteria andValidvpnumberLessThan(Integer value) {
            addCriterion("validVPNumber <", value, "validvpnumber");
            return (Criteria) this;
        }

        public Criteria andValidvpnumberLessThanOrEqualTo(Integer value) {
            addCriterion("validVPNumber <=", value, "validvpnumber");
            return (Criteria) this;
        }

        public Criteria andValidvpnumberIn(List<Integer> values) {
            addCriterion("validVPNumber in", values, "validvpnumber");
            return (Criteria) this;
        }

        public Criteria andValidvpnumberNotIn(List<Integer> values) {
            addCriterion("validVPNumber not in", values, "validvpnumber");
            return (Criteria) this;
        }

        public Criteria andValidvpnumberBetween(Integer value1, Integer value2) {
            addCriterion("validVPNumber between", value1, value2, "validvpnumber");
            return (Criteria) this;
        }

        public Criteria andValidvpnumberNotBetween(Integer value1, Integer value2) {
            addCriterion("validVPNumber not between", value1, value2, "validvpnumber");
            return (Criteria) this;
        }

        public Criteria andUseridIsNull() {
            addCriterion("userid is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("userid is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(Long value) {
            addCriterion("userid =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(Long value) {
            addCriterion("userid <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(Long value) {
            addCriterion("userid >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(Long value) {
            addCriterion("userid >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(Long value) {
            addCriterion("userid <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(Long value) {
            addCriterion("userid <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<Long> values) {
            addCriterion("userid in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<Long> values) {
            addCriterion("userid not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(Long value1, Long value2) {
            addCriterion("userid between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(Long value1, Long value2) {
            addCriterion("userid not between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("state is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("state is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(Integer value) {
            addCriterion("state =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(Integer value) {
            addCriterion("state <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(Integer value) {
            addCriterion("state >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("state >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(Integer value) {
            addCriterion("state <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(Integer value) {
            addCriterion("state <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<Integer> values) {
            addCriterion("state in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<Integer> values) {
            addCriterion("state not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(Integer value1, Integer value2) {
            addCriterion("state between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(Integer value1, Integer value2) {
            addCriterion("state not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andDateIsNull() {
            addCriterion("date is null");
            return (Criteria) this;
        }

        public Criteria andDateIsNotNull() {
            addCriterion("date is not null");
            return (Criteria) this;
        }

        public Criteria andDateEqualTo(Date value) {
            addCriterion("date =", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotEqualTo(Date value) {
            addCriterion("date <>", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateGreaterThan(Date value) {
            addCriterion("date >", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateGreaterThanOrEqualTo(Date value) {
            addCriterion("date >=", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateLessThan(Date value) {
            addCriterion("date <", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateLessThanOrEqualTo(Date value) {
            addCriterion("date <=", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateIn(List<Date> values) {
            addCriterion("date in", values, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotIn(List<Date> values) {
            addCriterion("date not in", values, "date");
            return (Criteria) this;
        }

        public Criteria andDateBetween(Date value1, Date value2) {
            addCriterion("date between", value1, value2, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotBetween(Date value1, Date value2) {
            addCriterion("date not between", value1, value2, "date");
            return (Criteria) this;
        }

        public Criteria andReplyIsNull() {
            addCriterion("reply is null");
            return (Criteria) this;
        }

        public Criteria andReplyIsNotNull() {
            addCriterion("reply is not null");
            return (Criteria) this;
        }

        public Criteria andReplyEqualTo(String value) {
            addCriterion("reply =", value, "reply");
            return (Criteria) this;
        }

        public Criteria andReplyNotEqualTo(String value) {
            addCriterion("reply <>", value, "reply");
            return (Criteria) this;
        }

        public Criteria andReplyGreaterThan(String value) {
            addCriterion("reply >", value, "reply");
            return (Criteria) this;
        }

        public Criteria andReplyGreaterThanOrEqualTo(String value) {
            addCriterion("reply >=", value, "reply");
            return (Criteria) this;
        }

        public Criteria andReplyLessThan(String value) {
            addCriterion("reply <", value, "reply");
            return (Criteria) this;
        }

        public Criteria andReplyLessThanOrEqualTo(String value) {
            addCriterion("reply <=", value, "reply");
            return (Criteria) this;
        }

        public Criteria andReplyLike(String value) {
            addCriterion("reply like", value, "reply");
            return (Criteria) this;
        }

        public Criteria andReplyNotLike(String value) {
            addCriterion("reply not like", value, "reply");
            return (Criteria) this;
        }

        public Criteria andReplyIn(List<String> values) {
            addCriterion("reply in", values, "reply");
            return (Criteria) this;
        }

        public Criteria andReplyNotIn(List<String> values) {
            addCriterion("reply not in", values, "reply");
            return (Criteria) this;
        }

        public Criteria andReplyBetween(String value1, String value2) {
            addCriterion("reply between", value1, value2, "reply");
            return (Criteria) this;
        }

        public Criteria andReplyNotBetween(String value1, String value2) {
            addCriterion("reply not between", value1, value2, "reply");
            return (Criteria) this;
        }

        public Criteria andScenictrafficIsNull() {
            addCriterion("scenictraffic is null");
            return (Criteria) this;
        }

        public Criteria andScenictrafficIsNotNull() {
            addCriterion("scenictraffic is not null");
            return (Criteria) this;
        }

        public Criteria andScenictrafficEqualTo(String value) {
            addCriterion("scenictraffic =", value, "scenictraffic");
            return (Criteria) this;
        }

        public Criteria andScenictrafficNotEqualTo(String value) {
            addCriterion("scenictraffic <>", value, "scenictraffic");
            return (Criteria) this;
        }

        public Criteria andScenictrafficGreaterThan(String value) {
            addCriterion("scenictraffic >", value, "scenictraffic");
            return (Criteria) this;
        }

        public Criteria andScenictrafficGreaterThanOrEqualTo(String value) {
            addCriterion("scenictraffic >=", value, "scenictraffic");
            return (Criteria) this;
        }

        public Criteria andScenictrafficLessThan(String value) {
            addCriterion("scenictraffic <", value, "scenictraffic");
            return (Criteria) this;
        }

        public Criteria andScenictrafficLessThanOrEqualTo(String value) {
            addCriterion("scenictraffic <=", value, "scenictraffic");
            return (Criteria) this;
        }

        public Criteria andScenictrafficLike(String value) {
            addCriterion("scenictraffic like", value, "scenictraffic");
            return (Criteria) this;
        }

        public Criteria andScenictrafficNotLike(String value) {
            addCriterion("scenictraffic not like", value, "scenictraffic");
            return (Criteria) this;
        }

        public Criteria andScenictrafficIn(List<String> values) {
            addCriterion("scenictraffic in", values, "scenictraffic");
            return (Criteria) this;
        }

        public Criteria andScenictrafficNotIn(List<String> values) {
            addCriterion("scenictraffic not in", values, "scenictraffic");
            return (Criteria) this;
        }

        public Criteria andScenictrafficBetween(String value1, String value2) {
            addCriterion("scenictraffic between", value1, value2, "scenictraffic");
            return (Criteria) this;
        }

        public Criteria andScenictrafficNotBetween(String value1, String value2) {
            addCriterion("scenictraffic not between", value1, value2, "scenictraffic");
            return (Criteria) this;
        }

        public Criteria andScenicfoodIsNull() {
            addCriterion("scenicfood is null");
            return (Criteria) this;
        }

        public Criteria andScenicfoodIsNotNull() {
            addCriterion("scenicfood is not null");
            return (Criteria) this;
        }

        public Criteria andScenicfoodEqualTo(String value) {
            addCriterion("scenicfood =", value, "scenicfood");
            return (Criteria) this;
        }

        public Criteria andScenicfoodNotEqualTo(String value) {
            addCriterion("scenicfood <>", value, "scenicfood");
            return (Criteria) this;
        }

        public Criteria andScenicfoodGreaterThan(String value) {
            addCriterion("scenicfood >", value, "scenicfood");
            return (Criteria) this;
        }

        public Criteria andScenicfoodGreaterThanOrEqualTo(String value) {
            addCriterion("scenicfood >=", value, "scenicfood");
            return (Criteria) this;
        }

        public Criteria andScenicfoodLessThan(String value) {
            addCriterion("scenicfood <", value, "scenicfood");
            return (Criteria) this;
        }

        public Criteria andScenicfoodLessThanOrEqualTo(String value) {
            addCriterion("scenicfood <=", value, "scenicfood");
            return (Criteria) this;
        }

        public Criteria andScenicfoodLike(String value) {
            addCriterion("scenicfood like", value, "scenicfood");
            return (Criteria) this;
        }

        public Criteria andScenicfoodNotLike(String value) {
            addCriterion("scenicfood not like", value, "scenicfood");
            return (Criteria) this;
        }

        public Criteria andScenicfoodIn(List<String> values) {
            addCriterion("scenicfood in", values, "scenicfood");
            return (Criteria) this;
        }

        public Criteria andScenicfoodNotIn(List<String> values) {
            addCriterion("scenicfood not in", values, "scenicfood");
            return (Criteria) this;
        }

        public Criteria andScenicfoodBetween(String value1, String value2) {
            addCriterion("scenicfood between", value1, value2, "scenicfood");
            return (Criteria) this;
        }

        public Criteria andScenicfoodNotBetween(String value1, String value2) {
            addCriterion("scenicfood not between", value1, value2, "scenicfood");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table scenicinfo_
     *
     * @mbggenerated do_not_delete_during_merge Wed Sep 20 12:56:34 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table scenicinfo_
     *
     * @mbggenerated Wed Sep 20 12:56:34 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}