package com.xianyo.feedbackmodule.dao.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserFeedbackDataExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table userfeedbackinfo_
     *
     * @mbggenerated Sun Sep 17 18:25:19 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table userfeedbackinfo_
     *
     * @mbggenerated Sun Sep 17 18:25:19 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table userfeedbackinfo_
     *
     * @mbggenerated Sun Sep 17 18:25:19 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userfeedbackinfo_
     *
     * @mbggenerated Sun Sep 17 18:25:19 CST 2017
     */
    public UserFeedbackDataExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userfeedbackinfo_
     *
     * @mbggenerated Sun Sep 17 18:25:19 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userfeedbackinfo_
     *
     * @mbggenerated Sun Sep 17 18:25:19 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userfeedbackinfo_
     *
     * @mbggenerated Sun Sep 17 18:25:19 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userfeedbackinfo_
     *
     * @mbggenerated Sun Sep 17 18:25:19 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userfeedbackinfo_
     *
     * @mbggenerated Sun Sep 17 18:25:19 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userfeedbackinfo_
     *
     * @mbggenerated Sun Sep 17 18:25:19 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userfeedbackinfo_
     *
     * @mbggenerated Sun Sep 17 18:25:19 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userfeedbackinfo_
     *
     * @mbggenerated Sun Sep 17 18:25:19 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userfeedbackinfo_
     *
     * @mbggenerated Sun Sep 17 18:25:19 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userfeedbackinfo_
     *
     * @mbggenerated Sun Sep 17 18:25:19 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table userfeedbackinfo_
     *
     * @mbggenerated Sun Sep 17 18:25:19 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andFeedbackidIsNull() {
            addCriterion("feedbackid is null");
            return (Criteria) this;
        }

        public Criteria andFeedbackidIsNotNull() {
            addCriterion("feedbackid is not null");
            return (Criteria) this;
        }

        public Criteria andFeedbackidEqualTo(Long value) {
            addCriterion("feedbackid =", value, "feedbackid");
            return (Criteria) this;
        }

        public Criteria andFeedbackidNotEqualTo(Long value) {
            addCriterion("feedbackid <>", value, "feedbackid");
            return (Criteria) this;
        }

        public Criteria andFeedbackidGreaterThan(Long value) {
            addCriterion("feedbackid >", value, "feedbackid");
            return (Criteria) this;
        }

        public Criteria andFeedbackidGreaterThanOrEqualTo(Long value) {
            addCriterion("feedbackid >=", value, "feedbackid");
            return (Criteria) this;
        }

        public Criteria andFeedbackidLessThan(Long value) {
            addCriterion("feedbackid <", value, "feedbackid");
            return (Criteria) this;
        }

        public Criteria andFeedbackidLessThanOrEqualTo(Long value) {
            addCriterion("feedbackid <=", value, "feedbackid");
            return (Criteria) this;
        }

        public Criteria andFeedbackidIn(List<Long> values) {
            addCriterion("feedbackid in", values, "feedbackid");
            return (Criteria) this;
        }

        public Criteria andFeedbackidNotIn(List<Long> values) {
            addCriterion("feedbackid not in", values, "feedbackid");
            return (Criteria) this;
        }

        public Criteria andFeedbackidBetween(Long value1, Long value2) {
            addCriterion("feedbackid between", value1, value2, "feedbackid");
            return (Criteria) this;
        }

        public Criteria andFeedbackidNotBetween(Long value1, Long value2) {
            addCriterion("feedbackid not between", value1, value2, "feedbackid");
            return (Criteria) this;
        }

        public Criteria andFeedbackcontextIsNull() {
            addCriterion("feedbackcontext is null");
            return (Criteria) this;
        }

        public Criteria andFeedbackcontextIsNotNull() {
            addCriterion("feedbackcontext is not null");
            return (Criteria) this;
        }

        public Criteria andFeedbackcontextEqualTo(String value) {
            addCriterion("feedbackcontext =", value, "feedbackcontext");
            return (Criteria) this;
        }

        public Criteria andFeedbackcontextNotEqualTo(String value) {
            addCriterion("feedbackcontext <>", value, "feedbackcontext");
            return (Criteria) this;
        }

        public Criteria andFeedbackcontextGreaterThan(String value) {
            addCriterion("feedbackcontext >", value, "feedbackcontext");
            return (Criteria) this;
        }

        public Criteria andFeedbackcontextGreaterThanOrEqualTo(String value) {
            addCriterion("feedbackcontext >=", value, "feedbackcontext");
            return (Criteria) this;
        }

        public Criteria andFeedbackcontextLessThan(String value) {
            addCriterion("feedbackcontext <", value, "feedbackcontext");
            return (Criteria) this;
        }

        public Criteria andFeedbackcontextLessThanOrEqualTo(String value) {
            addCriterion("feedbackcontext <=", value, "feedbackcontext");
            return (Criteria) this;
        }

        public Criteria andFeedbackcontextLike(String value) {
            addCriterion("feedbackcontext like", value, "feedbackcontext");
            return (Criteria) this;
        }

        public Criteria andFeedbackcontextNotLike(String value) {
            addCriterion("feedbackcontext not like", value, "feedbackcontext");
            return (Criteria) this;
        }

        public Criteria andFeedbackcontextIn(List<String> values) {
            addCriterion("feedbackcontext in", values, "feedbackcontext");
            return (Criteria) this;
        }

        public Criteria andFeedbackcontextNotIn(List<String> values) {
            addCriterion("feedbackcontext not in", values, "feedbackcontext");
            return (Criteria) this;
        }

        public Criteria andFeedbackcontextBetween(String value1, String value2) {
            addCriterion("feedbackcontext between", value1, value2, "feedbackcontext");
            return (Criteria) this;
        }

        public Criteria andFeedbackcontextNotBetween(String value1, String value2) {
            addCriterion("feedbackcontext not between", value1, value2, "feedbackcontext");
            return (Criteria) this;
        }

        public Criteria andUseridIsNull() {
            addCriterion("userid is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("userid is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(Long value) {
            addCriterion("userid =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(Long value) {
            addCriterion("userid <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(Long value) {
            addCriterion("userid >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(Long value) {
            addCriterion("userid >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(Long value) {
            addCriterion("userid <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(Long value) {
            addCriterion("userid <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<Long> values) {
            addCriterion("userid in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<Long> values) {
            addCriterion("userid not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(Long value1, Long value2) {
            addCriterion("userid between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(Long value1, Long value2) {
            addCriterion("userid not between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andFeedbacktitleIsNull() {
            addCriterion("feedbacktitle is null");
            return (Criteria) this;
        }

        public Criteria andFeedbacktitleIsNotNull() {
            addCriterion("feedbacktitle is not null");
            return (Criteria) this;
        }

        public Criteria andFeedbacktitleEqualTo(String value) {
            addCriterion("feedbacktitle =", value, "feedbacktitle");
            return (Criteria) this;
        }

        public Criteria andFeedbacktitleNotEqualTo(String value) {
            addCriterion("feedbacktitle <>", value, "feedbacktitle");
            return (Criteria) this;
        }

        public Criteria andFeedbacktitleGreaterThan(String value) {
            addCriterion("feedbacktitle >", value, "feedbacktitle");
            return (Criteria) this;
        }

        public Criteria andFeedbacktitleGreaterThanOrEqualTo(String value) {
            addCriterion("feedbacktitle >=", value, "feedbacktitle");
            return (Criteria) this;
        }

        public Criteria andFeedbacktitleLessThan(String value) {
            addCriterion("feedbacktitle <", value, "feedbacktitle");
            return (Criteria) this;
        }

        public Criteria andFeedbacktitleLessThanOrEqualTo(String value) {
            addCriterion("feedbacktitle <=", value, "feedbacktitle");
            return (Criteria) this;
        }

        public Criteria andFeedbacktitleLike(String value) {
            addCriterion("feedbacktitle like", value, "feedbacktitle");
            return (Criteria) this;
        }

        public Criteria andFeedbacktitleNotLike(String value) {
            addCriterion("feedbacktitle not like", value, "feedbacktitle");
            return (Criteria) this;
        }

        public Criteria andFeedbacktitleIn(List<String> values) {
            addCriterion("feedbacktitle in", values, "feedbacktitle");
            return (Criteria) this;
        }

        public Criteria andFeedbacktitleNotIn(List<String> values) {
            addCriterion("feedbacktitle not in", values, "feedbacktitle");
            return (Criteria) this;
        }

        public Criteria andFeedbacktitleBetween(String value1, String value2) {
            addCriterion("feedbacktitle between", value1, value2, "feedbacktitle");
            return (Criteria) this;
        }

        public Criteria andFeedbacktitleNotBetween(String value1, String value2) {
            addCriterion("feedbacktitle not between", value1, value2, "feedbacktitle");
            return (Criteria) this;
        }

        public Criteria andPicturedirIsNull() {
            addCriterion("picturedir is null");
            return (Criteria) this;
        }

        public Criteria andPicturedirIsNotNull() {
            addCriterion("picturedir is not null");
            return (Criteria) this;
        }

        public Criteria andPicturedirEqualTo(String value) {
            addCriterion("picturedir =", value, "picturedir");
            return (Criteria) this;
        }

        public Criteria andPicturedirNotEqualTo(String value) {
            addCriterion("picturedir <>", value, "picturedir");
            return (Criteria) this;
        }

        public Criteria andPicturedirGreaterThan(String value) {
            addCriterion("picturedir >", value, "picturedir");
            return (Criteria) this;
        }

        public Criteria andPicturedirGreaterThanOrEqualTo(String value) {
            addCriterion("picturedir >=", value, "picturedir");
            return (Criteria) this;
        }

        public Criteria andPicturedirLessThan(String value) {
            addCriterion("picturedir <", value, "picturedir");
            return (Criteria) this;
        }

        public Criteria andPicturedirLessThanOrEqualTo(String value) {
            addCriterion("picturedir <=", value, "picturedir");
            return (Criteria) this;
        }

        public Criteria andPicturedirLike(String value) {
            addCriterion("picturedir like", value, "picturedir");
            return (Criteria) this;
        }

        public Criteria andPicturedirNotLike(String value) {
            addCriterion("picturedir not like", value, "picturedir");
            return (Criteria) this;
        }

        public Criteria andPicturedirIn(List<String> values) {
            addCriterion("picturedir in", values, "picturedir");
            return (Criteria) this;
        }

        public Criteria andPicturedirNotIn(List<String> values) {
            addCriterion("picturedir not in", values, "picturedir");
            return (Criteria) this;
        }

        public Criteria andPicturedirBetween(String value1, String value2) {
            addCriterion("picturedir between", value1, value2, "picturedir");
            return (Criteria) this;
        }

        public Criteria andPicturedirNotBetween(String value1, String value2) {
            addCriterion("picturedir not between", value1, value2, "picturedir");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("state is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("state is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(Integer value) {
            addCriterion("state =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(Integer value) {
            addCriterion("state <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(Integer value) {
            addCriterion("state >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("state >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(Integer value) {
            addCriterion("state <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(Integer value) {
            addCriterion("state <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<Integer> values) {
            addCriterion("state in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<Integer> values) {
            addCriterion("state not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(Integer value1, Integer value2) {
            addCriterion("state between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(Integer value1, Integer value2) {
            addCriterion("state not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andDateIsNull() {
            addCriterion("date is null");
            return (Criteria) this;
        }

        public Criteria andDateIsNotNull() {
            addCriterion("date is not null");
            return (Criteria) this;
        }

        public Criteria andDateEqualTo(Date value) {
            addCriterion("date =", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotEqualTo(Date value) {
            addCriterion("date <>", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateGreaterThan(Date value) {
            addCriterion("date >", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateGreaterThanOrEqualTo(Date value) {
            addCriterion("date >=", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateLessThan(Date value) {
            addCriterion("date <", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateLessThanOrEqualTo(Date value) {
            addCriterion("date <=", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateIn(List<Date> values) {
            addCriterion("date in", values, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotIn(List<Date> values) {
            addCriterion("date not in", values, "date");
            return (Criteria) this;
        }

        public Criteria andDateBetween(Date value1, Date value2) {
            addCriterion("date between", value1, value2, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotBetween(Date value1, Date value2) {
            addCriterion("date not between", value1, value2, "date");
            return (Criteria) this;
        }

        public Criteria andReplyIsNull() {
            addCriterion("reply is null");
            return (Criteria) this;
        }

        public Criteria andReplyIsNotNull() {
            addCriterion("reply is not null");
            return (Criteria) this;
        }

        public Criteria andReplyEqualTo(String value) {
            addCriterion("reply =", value, "reply");
            return (Criteria) this;
        }

        public Criteria andReplyNotEqualTo(String value) {
            addCriterion("reply <>", value, "reply");
            return (Criteria) this;
        }

        public Criteria andReplyGreaterThan(String value) {
            addCriterion("reply >", value, "reply");
            return (Criteria) this;
        }

        public Criteria andReplyGreaterThanOrEqualTo(String value) {
            addCriterion("reply >=", value, "reply");
            return (Criteria) this;
        }

        public Criteria andReplyLessThan(String value) {
            addCriterion("reply <", value, "reply");
            return (Criteria) this;
        }

        public Criteria andReplyLessThanOrEqualTo(String value) {
            addCriterion("reply <=", value, "reply");
            return (Criteria) this;
        }

        public Criteria andReplyLike(String value) {
            addCriterion("reply like", value, "reply");
            return (Criteria) this;
        }

        public Criteria andReplyNotLike(String value) {
            addCriterion("reply not like", value, "reply");
            return (Criteria) this;
        }

        public Criteria andReplyIn(List<String> values) {
            addCriterion("reply in", values, "reply");
            return (Criteria) this;
        }

        public Criteria andReplyNotIn(List<String> values) {
            addCriterion("reply not in", values, "reply");
            return (Criteria) this;
        }

        public Criteria andReplyBetween(String value1, String value2) {
            addCriterion("reply between", value1, value2, "reply");
            return (Criteria) this;
        }

        public Criteria andReplyNotBetween(String value1, String value2) {
            addCriterion("reply not between", value1, value2, "reply");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table userfeedbackinfo_
     *
     * @mbggenerated do_not_delete_during_merge Sun Sep 17 18:25:19 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table userfeedbackinfo_
     *
     * @mbggenerated Sun Sep 17 18:25:19 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}