package com.xianyo.microblogmodule.dao.mapper;

import java.util.List;

import com.xianyo.microblogmodule.dao.pojo.MicroTagRelationData;
import org.apache.ibatis.annotations.Param;

public interface MicroTagRelationDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table microtagrelation_
     *
     * @mbggenerated Sun Sep 10 12:38:31 CST 2017
     */
    int countByExample(MicroTagRelationDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table microtagrelation_
     *
     * @mbggenerated Sun Sep 10 12:38:31 CST 2017
     */
    int deleteByExample(MicroTagRelationDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table microtagrelation_
     *
     * @mbggenerated Sun Sep 10 12:38:31 CST 2017
     */
    int insert(MicroTagRelationData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table microtagrelation_
     *
     * @mbggenerated Sun Sep 10 12:38:31 CST 2017
     */
    int insertSelective(MicroTagRelationData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table microtagrelation_
     *
     * @mbggenerated Sun Sep 10 12:38:31 CST 2017
     */
    List<MicroTagRelationData> selectByExample(MicroTagRelationDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table microtagrelation_
     *
     * @mbggenerated Sun Sep 10 12:38:31 CST 2017
     */
    int updateByExampleSelective(@Param("record") MicroTagRelationData record, @Param("example") MicroTagRelationDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table microtagrelation_
     *
     * @mbggenerated Sun Sep 10 12:38:31 CST 2017
     */
    int updateByExample(@Param("record") MicroTagRelationData record, @Param("example") MicroTagRelationDataExample example);
}