package com.xianyo.util.reportmodule.dao.mapper;

import com.xianyo.util.reportmodule.dao.pojo.UserReportData;
import com.xianyo.util.reportmodule.dao.pojo.UserReportDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserReportDataMapper {
    List<UserReportData> selectAll();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userreportinfo_
     *
     * @mbggenerated Mon Sep 18 15:28:29 CST 2017
     */
    int countByExample(UserReportDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userreportinfo_
     *
     * @mbggenerated Mon Sep 18 15:28:29 CST 2017
     */
    int deleteByExample(UserReportDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userreportinfo_
     *
     * @mbggenerated Mon Sep 18 15:28:29 CST 2017
     */
    int deleteByPrimaryKey(Long reportid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userreportinfo_
     *
     * @mbggenerated Mon Sep 18 15:28:29 CST 2017
     */
    int insert(UserReportData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userreportinfo_
     *
     * @mbggenerated Mon Sep 18 15:28:29 CST 2017
     */
    int insertSelective(UserReportData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userreportinfo_
     *
     * @mbggenerated Mon Sep 18 15:28:29 CST 2017
     */
    List<UserReportData> selectByExample(UserReportDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userreportinfo_
     *
     * @mbggenerated Mon Sep 18 15:28:29 CST 2017
     */
    UserReportData selectByPrimaryKey(Long reportid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userreportinfo_
     *
     * @mbggenerated Mon Sep 18 15:28:29 CST 2017
     */
    int updateByExampleSelective(@Param("record") UserReportData record, @Param("example") UserReportDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userreportinfo_
     *
     * @mbggenerated Mon Sep 18 15:28:29 CST 2017
     */
    int updateByExample(@Param("record") UserReportData record, @Param("example") UserReportDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userreportinfo_
     *
     * @mbggenerated Mon Sep 18 15:28:29 CST 2017
     */
    int updateByPrimaryKeySelective(UserReportData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userreportinfo_
     *
     * @mbggenerated Mon Sep 18 15:28:29 CST 2017
     */
    int updateByPrimaryKey(UserReportData record);
}