package com.xianyo.feedbackmodule.dao.mapper;

import java.util.List;

import com.xianyo.feedbackmodule.dao.pojo.UserFeedbackData;
import com.xianyo.feedbackmodule.dao.pojo.UserFeedbackDataExample;
import org.apache.ibatis.annotations.Param;

public interface UserFeedbackDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userfeedbackinfo_
     *
     * @mbggenerated Sun Sep 17 18:25:19 CST 2017
     */
    int countByExample(UserFeedbackDataExample example);

    //select all
    List<UserFeedbackData> selectAll();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userfeedbackinfo_
     *
     * @mbggenerated Sun Sep 17 18:25:19 CST 2017
     */
    int deleteByExample(UserFeedbackDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userfeedbackinfo_
     *
     * @mbggenerated Sun Sep 17 18:25:19 CST 2017
     */
    int deleteByPrimaryKey(Long feedbackid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userfeedbackinfo_
     *
     * @mbggenerated Sun Sep 17 18:25:19 CST 2017
     */
    int insert(UserFeedbackData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userfeedbackinfo_
     *
     * @mbggenerated Sun Sep 17 18:25:19 CST 2017
     */
    int insertSelective(UserFeedbackData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userfeedbackinfo_
     *
     * @mbggenerated Sun Sep 17 18:25:19 CST 2017
     */
    List<UserFeedbackData> selectByExample(UserFeedbackDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userfeedbackinfo_
     *
     * @mbggenerated Sun Sep 17 18:25:19 CST 2017
     */
    UserFeedbackData selectByPrimaryKey(Long feedbackid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userfeedbackinfo_
     *
     * @mbggenerated Sun Sep 17 18:25:19 CST 2017
     */
    int updateByExampleSelective(@Param("record") UserFeedbackData record, @Param("example") UserFeedbackDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userfeedbackinfo_
     *
     * @mbggenerated Sun Sep 17 18:25:19 CST 2017
     */
    int updateByExample(@Param("record") UserFeedbackData record, @Param("example") UserFeedbackDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userfeedbackinfo_
     *
     * @mbggenerated Sun Sep 17 18:25:19 CST 2017
     */
    int updateByPrimaryKeySelective(UserFeedbackData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userfeedbackinfo_
     *
     * @mbggenerated Sun Sep 17 18:25:19 CST 2017
     */
    int updateByPrimaryKey(UserFeedbackData record);
}