package com.xianyo.util.reportmodule.dao.pojo;

import java.util.Date;

public class UserReportData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userreportinfo_.reportid
     *
     * @mbggenerated Mon Sep 18 15:28:29 CST 2017
     */
    private Long reportid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userreportinfo_.aimid
     *
     * @mbggenerated Mon Sep 18 15:28:29 CST 2017
     */
    private Long aimid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userreportinfo_.reportreason
     *
     * @mbggenerated Mon Sep 18 15:28:29 CST 2017
     */
    private String reportreason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userreportinfo_.date
     *
     * @mbggenerated Mon Sep 18 15:28:29 CST 2017
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userreportinfo_.state
     *
     * @mbggenerated Mon Sep 18 15:28:29 CST 2017
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userreportinfo_.reply
     *
     * @mbggenerated Mon Sep 18 15:28:29 CST 2017
     */
    private String reply;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userreportinfo_.userid
     *
     * @mbggenerated Mon Sep 18 15:28:29 CST 2017
     */
    private Long userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userreportinfo_.reportid
     *
     * @return the value of userreportinfo_.reportid
     *
     * @mbggenerated Mon Sep 18 15:28:29 CST 2017
     */
    public Long getReportid() {
        return reportid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userreportinfo_.reportid
     *
     * @param reportid the value for userreportinfo_.reportid
     *
     * @mbggenerated Mon Sep 18 15:28:29 CST 2017
     */
    public void setReportid(Long reportid) {
        this.reportid = reportid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userreportinfo_.aimid
     *
     * @return the value of userreportinfo_.aimid
     *
     * @mbggenerated Mon Sep 18 15:28:29 CST 2017
     */
    public Long getAimid() {
        return aimid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userreportinfo_.aimid
     *
     * @param aimid the value for userreportinfo_.aimid
     *
     * @mbggenerated Mon Sep 18 15:28:29 CST 2017
     */
    public void setAimid(Long aimid) {
        this.aimid = aimid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userreportinfo_.reportreason
     *
     * @return the value of userreportinfo_.reportreason
     *
     * @mbggenerated Mon Sep 18 15:28:29 CST 2017
     */
    public String getReportreason() {
        return reportreason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userreportinfo_.reportreason
     *
     * @param reportreason the value for userreportinfo_.reportreason
     *
     * @mbggenerated Mon Sep 18 15:28:29 CST 2017
     */
    public void setReportreason(String reportreason) {
        this.reportreason = reportreason == null ? null : reportreason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userreportinfo_.date
     *
     * @return the value of userreportinfo_.date
     *
     * @mbggenerated Mon Sep 18 15:28:29 CST 2017
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userreportinfo_.date
     *
     * @param date the value for userreportinfo_.date
     *
     * @mbggenerated Mon Sep 18 15:28:29 CST 2017
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userreportinfo_.state
     *
     * @return the value of userreportinfo_.state
     *
     * @mbggenerated Mon Sep 18 15:28:29 CST 2017
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userreportinfo_.state
     *
     * @param state the value for userreportinfo_.state
     *
     * @mbggenerated Mon Sep 18 15:28:29 CST 2017
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userreportinfo_.reply
     *
     * @return the value of userreportinfo_.reply
     *
     * @mbggenerated Mon Sep 18 15:28:29 CST 2017
     */
    public String getReply() {
        return reply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userreportinfo_.reply
     *
     * @param reply the value for userreportinfo_.reply
     *
     * @mbggenerated Mon Sep 18 15:28:29 CST 2017
     */
    public void setReply(String reply) {
        this.reply = reply == null ? null : reply.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userreportinfo_.userid
     *
     * @return the value of userreportinfo_.userid
     *
     * @mbggenerated Mon Sep 18 15:28:29 CST 2017
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userreportinfo_.userid
     *
     * @param userid the value for userreportinfo_.userid
     *
     * @mbggenerated Mon Sep 18 15:28:29 CST 2017
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    @Override
    public String toString() {
        return "UserReportData{" +
                "reportid=" + reportid +
                ", aimid=" + aimid +
                ", reportreason='" + reportreason + '\'' +
                ", date=" + date +
                ", state=" + state +
                ", reply='" + reply + '\'' +
                ", userid=" + userid +
                '}';
    }
}